{% set name = "tensorflow-metadata" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorflow-metadata/tensorflow_metadata-{{ version }}-py3-none-any.whl
  sha256: 05e3805193ac4722b399ec0ebe21fe73625867e0093f016062b5f9f39b2bbbe7

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed tensorflow_metadata-{{ version }}-py3-none-any.whl

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - googleapis-common-protos >=1.52.0,<2
    - protobuf >=3.7,<4
    - absl-py >=0.9,<0.13
    - python >=3.6,<4.0

test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata/
  summary: Library and standards for schema and statistics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
