{% set name = "tensorflow-metadata" %}
{% set version = "1.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorflow-metadata/tensorflow_metadata-{{ version }}-py3-none-any.whl
  sha256: 2ce72ea31d78a00c0c74c6d465482335aa5cb2a3b2a104dedba0b258bc7bb18a

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation tensorflow_metadata-{{ version }}-py3-none-any.whl



requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - googleapis-common-protos >=1.56.4,<2  # [py>=311]
    - protobuf >=4.25.2,<6  # [py>=311]
    - protobuf >=3.20.3,<4.21  # [py<311]
    - absl-py >=0.9,<3.0.0
test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata/
  summary: Library and standards for schema and statistics.
  description: TensorFlow Metadata provides standard representations for metadata that are useful when training machine learning models with TensorFlow.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://pypi.org/project/tensorflow-metadata/
  dev_url: https://github.com/tensorflow/metadata

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
