{% set name = "tensorflow-metadata" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorflow-metadata/tensorflow_metadata-{{ version }}-py3-none-any.whl
  sha256: e3ff528496105c0d73b2a402877525b1695635378fbe5c1b47ac7b3780816bb3

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed tensorflow_metadata-{{ version }}-py3-none-any.whl

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - googleapis-common-protos >=1.52.0,<2
    - tensorflow
    - python >=3.7

test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata/
  summary: Library and standards for schema and statistics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
