{% set name = "tensorflow-metadata" %}
{% set version = "1.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/py3/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}-py3-none-any.whl
  sha256: 452912e6398b3cb7302f0de6139dea794b3be1bd0eb40e6765eb3a04e51ea991

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation {{ name|replace("-", "_") }}-{{ version }}-py3-none-any.whl

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - absl-py >=0.9,<3.0.0
    - googleapis-common-protos >=1.56.4,<2 # [py>=311]
    - protobuf >=4.25.2 # [py>=311]
    - protobuf >=4.21.6,<=6.32 # [py<311]

test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata
  summary: Library and standards for schema and statistics.
  description: TensorFlow Metadata provides standard representations for metadata that are useful when training machine learning models with TensorFlow.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://pypi.org/project/tensorflow-metadata
  dev_url: https://github.com/tensorflow/metadata

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
