<<<<<<< HEAD
{% set version = "0.14.0" %}

package:
  name: tensorflow-metadata
  version: {{ version }}

source:
  url: https://github.com/tensorflow/metadata/archive/v{{ version }}.tar.gz
  sha256: f14b88f3b72b3419ca95c016dd4c6251179f33f375deceb5d9bf3d3bf51ba9cc

build:
  number: 1
  # This is a noarch: python package, it contains no compiled code but a
  # compiler is required to convert protocol buffer definitions.
  # The build has only been tested on linux-64
  noarch: python
  skip: True  # [not linux]
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel
  host:
    - python
    - pip
  run:
    - python
    - protobuf >=3.7,<4
    - googleapis-common-protos
    - tensorflow

test:
  imports:
    - tensorflow_metadata

about:
  home: https://www.tensorflow.org/metadata
  license: Apache-2.0
  license_file: LICENSE
  summary: Library and standards for schema and statistics.

extra:
  recipe-maintainers:
    - jjhelmus
=======
{% set name = "tensorflow-metadata" %}
{% set version = "1.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorflow-metadata/tensorflow_metadata-{{ version }}-py3-none-any.whl
  sha256: cb84d8e159128aeae7b3f6013ccd7969c69d2e6d1a7b255dbfa6f5344d962986

build:
  number: 0
  noarch: python


requirements:
  host:
    - pip
    - python >=3.7
  run:
    - googleapis-common-protos >=1.56.4,<2
    - protobuf >=4.25.2,<5
    - absl-py >=0.9,<3.0.0 
    - python >=3.7
test:
  imports:
    - tensorflow_metadata
    - tensorflow_metadata.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-metadata/
  summary: Library and standards for schema and statistics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - ngam
>>>>>>> conda-forge/main
